# Generated by Django 3.2.5 on 2021-07-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='update_date',
        ),
    ]
